"use client";

import { useEffect, useMemo, useState } from "react";
import type { SavedReport } from "../lib/report-storage";

type ReportType = "one-page" | "issue-response";
type Period = "7d" | "30d" | "1y" | "all";
type ProviderResult = { status: "success" | "error"; text?: string; sources?: Array<{ title: string; url: string }>; error?: string };
type SearchResponse = { openai: ProviderResult | null; gemini: ProviderResult | null };
type TemplateState = { status: "idle" | "loading" | "success" | "error"; filename?: string; markdown?: string; structure?: { headings: Array<{ level: number; text: string }>; tables: number; paragraphs: number }; error?: string };

const sourceOptions = [
  { id: "public", label: "정부·공공기관", detail: "정책·통계·공식 발표" }, { id: "research", label: "연구·학술", detail: "논문·연구보고서" }, { id: "news", label: "뉴스", detail: "국내외 주요 언론" }, { id: "business", label: "기업", detail: "산업·기업 동향" }, { id: "global", label: "국제기구", detail: "OECD·UN·IMF 등" },
];
const periodLabels: Record<Period, string> = { "7d": "최근 7일", "30d": "최근 30일", "1y": "최근 1년", all: "전체 기간" };
const API_SESSION_KEYS = { openai: "issue-brief-openai-api-key", gemini: "issue-brief-gemini-api-key" } as const;

function ResultCard({ label, result, configured }: { label: string; result: ProviderResult | null; configured: boolean }) {
  if (!configured) return <article className="provider-card unavailable"><div className="provider-card-header"><strong>{label}</strong><span>키 미설정</span></div><p>이 API 키를 입력하면 검색 결과가 표시됩니다.</p></article>;
  if (!result) return null;
  if (result.status === "error") return <article className="provider-card provider-error"><div className="provider-card-header"><strong>{label}</strong><span className="error-badge">오류</span></div><p>{result.error}</p></article>;
  return <article className="provider-card"><div className="provider-card-header"><strong>{label}</strong><span className="success-badge"><span className="status-dot" /> 검색 완료</span></div><div className="provider-text">{result.text}</div>{result.sources && result.sources.length > 0 && <div className="source-block"><strong>참고 출처 ({result.sources.length})</strong><ol>{result.sources.map((source, index) => <li key={`${source.url}-${index}`}><a href={source.url} target="_blank" rel="noreferrer">[{index + 1}] {source.title || source.url}</a></li>)}</ol></div>}</article>;
}

export default function Home() {
  const [query, setQuery] = useState(""); const [reportType, setReportType] = useState<ReportType>("one-page"); const [period, setPeriod] = useState<Period>("30d"); const [sources, setSources] = useState<string[]>(["public", "research", "news"]);
  const [openaiKey, setOpenaiKey] = useState(""); const [geminiKey, setGeminiKey] = useState(""); const [sessionState, setSessionState] = useState<"empty" | "saved" | "changed">("empty");
  const [searchState, setSearchState] = useState<"idle" | "loading" | "done">("idle"); const [searchResponse, setSearchResponse] = useState<SearchResponse | null>(null); const [apiError, setApiError] = useState(""); const [template, setTemplate] = useState<TemplateState>({ status: "idle" }); const [saveState, setSaveState] = useState<"idle" | "saved" | "error">("idle"); const [savedCount, setSavedCount] = useState(0);
  useEffect(() => { const openai = sessionStorage.getItem(API_SESSION_KEYS.openai) ?? ""; const gemini = sessionStorage.getItem(API_SESSION_KEYS.gemini) ?? ""; setOpenaiKey(openai); setGeminiKey(gemini); void fetch("/api/reports").then(async (response) => response.ok ? response.json() as Promise<{ reports: SavedReport[] }> : { reports: [] }).then((data) => setSavedCount(data.reports.length)).catch(() => setSavedCount(0)); if (openai || gemini) setSessionState("saved"); }, []);
  const sourceSummary = useMemo(() => sourceOptions.filter((source) => sources.includes(source.id)).map((source) => source.label), [sources]);
  const updateKey = (provider: "openai" | "gemini", value: string) => { if (provider === "openai") setOpenaiKey(value); else setGeminiKey(value); setSessionState("changed"); setApiError(""); };
  const saveSession = () => { if (openaiKey.trim()) sessionStorage.setItem(API_SESSION_KEYS.openai, openaiKey.trim()); else sessionStorage.removeItem(API_SESSION_KEYS.openai); if (geminiKey.trim()) sessionStorage.setItem(API_SESSION_KEYS.gemini, geminiKey.trim()); else sessionStorage.removeItem(API_SESSION_KEYS.gemini); setSessionState(openaiKey.trim() || geminiKey.trim() ? "saved" : "empty"); };
  const clearSession = () => { sessionStorage.removeItem(API_SESSION_KEYS.openai); sessionStorage.removeItem(API_SESSION_KEYS.gemini); setOpenaiKey(""); setGeminiKey(""); setSessionState("empty"); setApiError(""); };
  const resetForm = () => { setQuery(""); setReportType("one-page"); setPeriod("30d"); setSources(["public", "research", "news"]); setSearchResponse(null); setSearchState("idle"); setApiError(""); setSaveState("idle"); };
  const analyzeTemplate = async (file: File) => { setTemplate({ status: "loading", filename: file.name }); try { const formData = new FormData(); formData.append("file", file); const response = await fetch("/api/template", { method: "POST", body: formData }); const data = await response.json() as TemplateState; if (!response.ok) throw new Error(data.error || "문서 분석에 실패했습니다."); setTemplate({ status: "success", filename: data.filename, markdown: data.markdown, structure: data.structure }); } catch (error) { setTemplate({ status: "error", filename: file.name, error: error instanceof Error ? error.message : "문서 분석에 실패했습니다." }); } };
  const createDraft = async () => { if (!openaiKey.trim() && !geminiKey.trim()) { setApiError("보고서 초안을 생성하려면 OpenAI 또는 Gemini API 키를 입력해 주세요."); return; } setApiError(""); setSearchState("loading"); setSearchResponse(null); try { const response = await fetch("/api/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query, reportType, period, periodLabel: periodLabels[period], sources: sourceSummary, openaiKey, geminiKey, templateMarkdown: template.markdown, templateFilename: template.filename }) }); const data = await response.json() as SearchResponse & { error?: string }; if (!response.ok) throw new Error(data.error || "검색 요청에 실패했습니다."); setSearchResponse(data); } catch (error) { setApiError(error instanceof Error ? error.message : "검색 요청에 실패했습니다."); } finally { setSearchState("done"); } };
  const saveCurrentReport = async () => { if (!searchResponse || !hasAnyResult) return; setSaveState("idle"); try { const response = await fetch("/api/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query, reportType, period, sources: sourceSummary, templateFilename: template.filename, openai: searchResponse.openai, gemini: searchResponse.gemini }) }); const data = await response.json() as { report?: SavedReport; error?: string }; if (!response.ok) throw new Error(data.error || "Supabase 저장에 실패했습니다."); setSavedCount((count) => count + 1); setSaveState("saved"); } catch (error) { setSaveState("error"); setApiError(error instanceof Error ? error.message : "Supabase 저장에 실패했습니다."); } };
  const openSavedReports = () => window.open("/reports", "_blank", "noopener,noreferrer");
  const toggleSource = (id: string) => setSources((current) => current.includes(id) ? current.filter((source) => source !== id) : [...current, id]);
  const hasAnyResult = Boolean(searchResponse?.openai || searchResponse?.gemini);

  return <main className="app-shell">
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark" aria-hidden="true"><span>i</span></div><div><p className="eyebrow">PUBLIC ISSUE INTELLIGENCE</p><h1>현안 브리프</h1></div></div><div className="topbar-meta"><span className="status-dot" /> Web Search 연결됨 <span className="divider" /> 2026. 08. 17</div></header>
    <section className="intro-block"><p className="section-kicker">ISSUE RESPONSE · REPORT DRAFT</p><h2>이슈를 입력하면,<br /><em>대응의 방향</em>이 보입니다.</h2><p className="intro-copy">키워드나 기사 본문을 바탕으로 최신 현안을 정리하고<br className="desktop-break" /> 바로 보고할 수 있는 초안을 만들어보세요.</p></section>
    <section className="api-settings panel" aria-labelledby="api-settings-title"><div className="api-settings-copy"><div className="api-heading-line"><span className="step-label">SESSION SETUP</span><span className="session-badge"><span className="status-dot" /> {sessionState === "saved" ? "세션에 저장됨" : sessionState === "changed" ? "저장 전 변경됨" : "저장된 키 없음"}</span></div><h3 id="api-settings-title">API 키 설정</h3><p>검색에 사용할 API 키를 입력하세요. 키는 현재 브라우저 탭의 세션에만 저장됩니다.</p></div><div className="api-settings-fields"><label className="api-key-field"><span>OpenAI API 키</span><input type="password" value={openaiKey} onChange={(event) => updateKey("openai", event.target.value)} placeholder="sk-••••••••••••••••" autoComplete="off" /><small>Responses API · Web Search</small></label><label className="api-key-field"><span>Gemini API 키</span><input type="password" value={geminiKey} onChange={(event) => updateKey("gemini", event.target.value)} placeholder="AIza••••••••••••••••" autoComplete="off" /><small>generateContent · Google Search</small></label></div><div className="api-settings-actions"><p className="session-notice"><span>i</span> 탭을 닫으면 API 키가 삭제됩니다. 키는 서버 로그나 결과에 출력하지 않습니다.</p><div className="session-buttons"><button type="button" className="secondary-button" onClick={saveSession}>세션 저장</button><button type="button" className="text-button" onClick={clearSession}>세션 비우기</button></div></div></section>
    <section className="template-upload panel" aria-labelledby="template-title"><div className="template-upload-copy"><div className="api-heading-line"><span className="step-label">05 · TEMPLATE</span>{template.status === "success" && <span className="session-badge"><span className="status-dot" /> 분석 완료</span>}{template.status === "loading" && <span className="session-badge">분석 중…</span>}</div><h3 id="template-title">보고서 양식 분석</h3><p>기존 한글 파일이나 문서 양식을 올리면 제목·항목·문단 순서를 분석해 보고서 생성에 반영합니다.</p></div><label className="upload-dropzone"><input type="file" accept=".hwp,.hwpx,.docx,.pdf,.xlsx,.xls" onChange={(event) => { const file = event.target.files?.[0]; if (file) void analyzeTemplate(file); event.currentTarget.value = ""; }} /><span className="upload-icon">↑</span><span><strong>{template.status === "loading" ? "문서 양식을 분석하고 있습니다…" : "파일을 선택하거나 여기에 끌어놓으세요"}</strong><small>.hwp · .hwpx · .docx · .pdf · .xlsx · .xls / 최대 30MB</small></span></label>{template.filename && <div className={template.status === "error" ? "template-status error" : "template-status"}><span>{template.status === "error" ? "!" : "✓"}</span><strong>{template.filename}</strong>{template.status === "success" && template.structure && <small>분석 완료 · 제목 {template.structure.headings.length}개 · 표 {template.structure.tables}개 · 문단 {template.structure.paragraphs}개</small>}{template.status === "error" && <small>{template.error}</small>}</div>}{template.status === "success" && template.markdown && <details className="template-preview"><summary>분석된 양식 미리보기</summary><pre>{template.markdown.slice(0, 5000)}</pre></details>}</section>
    <div className="workspace-grid">
      <section className="panel input-panel" aria-labelledby="input-title"><div className="panel-heading"><div><span className="step-label">01</span><h3 id="input-title">이슈 입력</h3></div><span className="required-label">필수</span></div><label className="textarea-wrap"><span className="sr-only">키워드 또는 뉴스 기사 본문</span><textarea value={query} onChange={(event) => setQuery(event.target.value)} placeholder={'키워드 또는 뉴스 기사 본문을 입력하세요.\n예) 지역 소멸 대응을 위한 청년 정착 지원 정책'} maxLength={2000} /><span className="char-count">{query.length.toLocaleString()} / 2,000</span></label><div className="form-section"><div className="field-label"><span className="step-label">02</span><span>보고서 유형</span></div><div className="segmented-control"><button className={reportType === "one-page" ? "selected" : ""} onClick={() => setReportType("one-page")} type="button"><span className="radio-dot" /> 보고용 1장 페이퍼</button><button className={reportType === "issue-response" ? "selected" : ""} onClick={() => setReportType("issue-response")} type="button"><span className="radio-dot" /> 현황 · 문제점 · 대응방향</button></div></div><div className="form-section"><div className="field-label"><span className="step-label">03</span><span>검색 기간</span></div><div className="period-grid">{(Object.keys(periodLabels) as Period[]).map((value) => <button key={value} className={period === value ? "period-option selected" : "period-option"} onClick={() => setPeriod(value)} type="button">{periodLabels[value]}</button>)}</div></div><div className="form-section sources-section"><div className="field-label"><span className="step-label">04</span><span>검색 소스</span><span className="field-hint">복수 선택 가능</span></div><div className="source-list">{sourceOptions.map((source) => <label className="source-option" key={source.id}><input type="checkbox" checked={sources.includes(source.id)} onChange={() => toggleSource(source.id)} /><span className="fake-checkbox">✓</span><span><strong>{source.label}</strong><small>{source.detail}</small></span></label>)}</div></div>{apiError && <p className="api-error" role="alert"><span>!</span>{apiError}</p>}<div className="form-actions"><button className="primary-button" onClick={createDraft} type="button" disabled={searchState === "loading"}><span>{searchState === "loading" ? "검색 엔진에서 확인 중…" : "보고서 초안 생성하기"}</span><span className="button-arrow">↗</span></button>{searchState === "done" && hasAnyResult && <button type="button" className="save-button" onClick={saveCurrentReport}>{saveState === "saved" ? "저장 완료" : "보고서 저장"}</button>}<button type="button" className="reset-button" onClick={resetForm}>입력·결과 리셋</button></div>{saveState === "error" && <p className="save-error" role="alert">보고서를 브라우저에 저장하지 못했습니다.</p>}{saveState === "saved" && <button type="button" className="saved-reports-link" onClick={openSavedReports}>새 탭에서 저장 보고서 확인 ↗</button>}<p className="privacy-note"><span>✦</span> 검색 결과는 선택한 API별로 분리해 표시합니다. {savedCount > 0 && `저장된 보고서 ${savedCount}건`}</p></section>
      <section className="panel result-panel" aria-labelledby="result-title"><div className="result-header"><div><span className="step-label">OUTPUT</span><h3 id="result-title">생성 결과</h3></div>{searchState === "loading" && <span className="result-ready">검색 중…</span>}{searchState === "done" && hasAnyResult && <span className="result-ready"><span className="status-dot" /> 결과 수신</span>}</div>{searchState === "idle" ? <div className="empty-result"><div className="empty-orbit"><div className="empty-center">✦</div><i /><i /><i /></div><h4>아직 생성된 초안이 없습니다.</h4><p>API 키와 이슈를 입력하고<br />초안 생성 버튼을 눌러주세요.</p><div className="empty-line" /><span className="empty-tip">TIP · 양식을 업로드하면 기존 보고서 구조를 따라갑니다.</span></div> : searchState === "loading" ? <div className="loading-result"><div className="loading-spinner" /><h4>최신 웹 정보를 검색하고 있습니다.</h4><p>OpenAI Web Search와 Gemini Google Search를 병렬로 호출합니다.</p></div> : <div className="provider-results"><ResultCard label="OpenAI · Web Search" result={searchResponse?.openai ?? null} configured={Boolean(openaiKey.trim())} /><ResultCard label="Gemini · Google Search Grounding" result={searchResponse?.gemini ?? null} configured={Boolean(geminiKey.trim())} /></div>}</section>
    </div>
    <footer className="site-footer"><span>현안 브리프 <b>·</b> 이슈 대응·성과 보고서 초안 생성기</span><span>Prepared for decision makers</span></footer>
  </main>;
}
